# This file was generated by GoReleaser. DO NOT EDIT.
cask "gurdy" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2d9202b519e4a661f5b91fb636e924553ff69a9787f18aa2065de3efcba45e94"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a138aff5a160d10cb0981b168a6008a0dfdedc798ebcc8a781c02128d7c2cb69"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "02ee3be62640cf1eecb33edce92b2790fba7534fb1a042afecbf8b153ff88277"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b65e825a6415b06e74ab98e4d6adc4e7fa3d33c6e6c087cb4d09f60a31ef8511"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gurdy"
  desc "A flight recorder for AI agents — governs agent tool calls and writes a verifiable decision ledger"
  homepage "https://github.com/GurdyAI/gurdy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gurdy-proxy"
  binary "gurdy-verify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/gurdy-proxy"],
                     sudo: false
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/gurdy-verify"],
                     sudo: false
    end
  end

  # No zap stanza required

end
