# This file was generated by GoReleaser. DO NOT EDIT.
cask "gurdy" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1a1b2d0c557ab043cc32da0bf916920b882f2da7eefe56f4e91d1f7cdcd5524b"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "be838d14bd7e0089d6aa75ea06e30953d4868329c561ef9d2b3cd2a47f7380f2"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "09c3eb0c067388fe1e01f41011d3ff2754cea8bb694220eba5a9e58c027f6c67"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f325c3d365690e5ad093eac2474527298e5947c84f254e7e441d584f650909c9"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gurdy"
  desc "A flight recorder for AI agents — governs agent tool calls and writes a verifiable decision ledger"
  homepage "https://github.com/GurdyAI/gurdy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gurdy-proxy"
  binary "gurdy-verify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/gurdy-proxy"],
                     sudo: false
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/gurdy-verify"],
                     sudo: false
    end
  end

  # No zap stanza required

end
