# This file was generated by GoReleaser. DO NOT EDIT.
cask "gurdy" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b400a96baef8434f1fdb0b5364a41ce299e05afbe01f993dfc24225424cb5dd9"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0a5de3a765d687be237e9d3c85ae0919cbac1b417955f36026f2b4d0d1343261"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e2921e0e0246c2ad8ad534e3caac877f0079c9421f39f42acd81b643972e43e"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce60e1e12a0fe4d25879b9ee3de27d69dcf814f2ae7ed5894d6839ff7d1db78f"
      url "https://github.com/GurdyAI/gurdy/releases/download/v#{version}/gurdy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gurdy"
  desc "A flight recorder for AI agents — governs agent tool calls and writes a verifiable decision ledger"
  homepage "https://github.com/GurdyAI/gurdy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gurdy-proxy"
  binary "gurdy-verify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/gurdy-proxy"],
                     sudo: false
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/gurdy-verify"],
                     sudo: false
    end
  end

  # No zap stanza required

end
